version: '3.3'

services:
  api:
    container_name: currency-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=123456
    ports: 
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - currency-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - currency-api
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=123456

networks:
    currency-api:
      driver: bridge

  
  